# wait
model: 'AIM-9-TRAILS'  # Name this after the Object --> It will be the folder name where weights are saved
model_dir: 'data/model' # Weights are saved/loaded from {model_dir}/{model}/{epoch-number}.pth
network: 'res'   # ResNet18 with modifications for dense prediction
heads: 
    vote_dim: 30  # Set this to 2 (K + 1)  + 2 where K is the number of keypoints (excluding center)

task: 'pvnet'
gpus: (0, 1)
resume: true
cls_type: AIM-9-SIDEWINDER-TRAILS 
symmetric: True

#transfer: 'data/model'  # WIP
symmetry: (1, 1, 4)  # WIP

train:
    optim: 'adam'
    lr: 1e-3
    epoch: 6000
    milestones: (20, 40, 60, 80) #, 100, 120, 160, 180, 200, 220)
    gamma: 0.9 # 0.5
    batch_size: 32
    dataset: 'CustomTrain'
    cropresize_rate: 1.0
    rotate_rate: 1.0
    rotate_min: -30
    rotate_max: 30
    weight_decay: 0.
    batch_sampler: 'image_size'
test:
    dataset: 'CustomTest'
    batch_size: 1
    batch_sampler: 'image_size'

